name: WorldMagic
version: '2.1.0'
main: com.github.vevc.WorldMagicPlugin
api-version: '1.21'
author: vevc
description: Multi-protocol proxy server plugin for PaperMC/Fabric
website: https://github.com/zv201413/PaperMC_WorldMagic
